#!/usr/bin/perl
# translate TX Power Limit Matrix declarations to header files
#print $#ARGV;

# Slurp all the input
undef $/;
# Create an array of unsigned chars from input
#@flist = <STDIN>;
print "// =========================================\n";
print "// TXPWR.h is auto-generated by tplmt2h.pl.\n";
print "// =========================================\n\n";
print "#ifndef _TXPWR_H\n#define _TXPWR_H\n";
@flist = split(/ /, substr(<STDIN>,0,length(<STDIN>)-1));
@sorted = sort { $a <=> $b } @flist;
@sorted = sort { length($a) <=> length($b) } @flist;

$i = 1;
@rID; # regDomain
while ($i<=$#sorted) {
   my @str;
   @str = split(/_/, $sorted[$i]);
   $rID[$i]=$str[$#str];
   $i++;
}
$max_rID = $rID[$#rID];
print "#define TXPWR_LMT_MAX $max_rID\n";
foreach my $fname (@sorted)
{
   print "#include \"data_$fname.c\"\n";
}

print "unsigned char *data_TXPWR_LMT_array\[\]={\n";
$i = 0;
$j = 1;
while ($i <= $max_rID ) {
   if($i == $rID[$j]) {
      print "\tdata_$sorted[$j],\n";
      $j++;
   } 
   else {
      print "\tNULL,\n";
   }
   $i++;
}
print "};\n";

print "unsigned char *data_TXPWR_LMT_array_end\[\]={\n";
$i = 0;
$j = 1;
while ($i <= $max_rID ) {
   if($i == $rID[$j]) {
      print "\tdata_$sorted[$j]+sizeof(data_$sorted[$j]),\n";
      $j++;
   }
   else {
      print "\tNULL,\n";
   }
   $i++;
}
print "};\n";
print "#endif";

