// =========================================
// TXPWR.h is auto-generated by tplmt2h.pl.
// =========================================

#ifndef _TXPWR_H
#define _TXPWR_H
#define TXPWR_LMT_MAX 6
#include "data_TXPWR_LMT_92c.c"
#include "data_TXPWR_LMT_92c_1.c"
#include "data_TXPWR_LMT_92c_2.c"
#include "data_TXPWR_LMT_92c_3.c"
#include "data_TXPWR_LMT_92c_4.c"
#include "data_TXPWR_LMT_92c_5.c"
#include "data_TXPWR_LMT_92c_6.c"
unsigned char *data_TXPWR_LMT_array[]={
	NULL,
	data_TXPWR_LMT_92c_1,
	data_TXPWR_LMT_92c_2,
	data_TXPWR_LMT_92c_3,
	data_TXPWR_LMT_92c_4,
	data_TXPWR_LMT_92c_5,
	data_TXPWR_LMT_92c_6,
};
unsigned char *data_TXPWR_LMT_array_end[]={
	NULL,
	data_TXPWR_LMT_92c_1+sizeof(data_TXPWR_LMT_92c_1),
	data_TXPWR_LMT_92c_2+sizeof(data_TXPWR_LMT_92c_2),
	data_TXPWR_LMT_92c_3+sizeof(data_TXPWR_LMT_92c_3),
	data_TXPWR_LMT_92c_4+sizeof(data_TXPWR_LMT_92c_4),
	data_TXPWR_LMT_92c_5+sizeof(data_TXPWR_LMT_92c_5),
	data_TXPWR_LMT_92c_6+sizeof(data_TXPWR_LMT_92c_6),
};
#endif