/* MiniDLNA Project
 * http://sourceforge.net/projects/minidlna/
 * (c) 2008-2009 Justin Maggard
 * generated by ./genconfig.sh on Thu Jun 14 16:23:57 CST 2012 */
#ifndef __CONFIG_H__
#define __CONFIG_H__

#define OS_NAME			"Linux"
#define OS_VERSION		"Linux/2.6"
#define OS_URL			"http://www.linux.org/"

/* full path of the file database */
#define DEFAULT_DB_PATH		"/tmp/minidlna"

/* full path of the log directory */
#define DEFAULT_LOG_PATH	"/var/log"

/* Comment the following line to use home made daemonize() func instead
 * of BSD daemon() */
/*#define USE_DAEMON*/

/* Enable if the system inotify.h exists.  Otherwise our own inotify.h will be used. */
#define HAVE_INOTIFY_H

/* Enable if the system iconv.h exists.  ID3 tag reading in various character sets will not work properly otherwise. */
#define HAVE_ICONV_H

/* Enable if the system libintl.h exists for NLS support. */
/*#define ENABLE_NLS*/

/* Enable NETGEAR-specific tweaks. */
/*#define NETGEAR*/
/* Enable ReadyNAS-specific tweaks. */
/*#define READYNAS*/
/* Compile in TiVo support. */
/*#define TIVO_SUPPORT*/
/* Enable PnPX support. */
#define PNPX 0

#define ALPHA_NETWORKS

#ifdef ALPHA_NETWORKS
  #define ALPHA_MANUFACTURERURL    "http://www.dlink.com/"
  #define ALPHA_MANUFACTURER	   "D-Link Corporation"
  #define ALPHA_MODELNAME	       "D-Link Router" //"Windows Media Connect compatible"
  #define ALPHA_MODELDESCRIPTION   "D-Link Router"
  #define ALPHA_MODELURL	       "http://www.dlink.com/"
#endif


#endif //__CONFIG_H__
