#!/bin/sh
if [ "$1" = "" ]; then
	echo -e "\033[31m[$0]: no rootfs path specified !\033[0m"
	exit 9
fi

echo "[$0]: makeing nodes ..."
[ -d $1/dev ] || mkdir $1/dev
mknod $1/dev/mem		c	1	1
mknod $1/dev/kmem		c	1	2
mknod $1/dev/null		c	1	3
mknod $1/dev/port		c	1	4
mknod $1/dev/zero		c	1	5
mknod $1/dev/full		c	1	7
mknod $1/dev/random		c	1	8
mknod $1/dev/urandom	c	1	9
mknod $1/dev/rdm0		c	220	0
mknod $1/dev/gpio		c	101	0
mknod $1/dev/rtldrv		c	253	0
[ -d $1/dev/pty ] || mkdir $1/dev/pty
mknod $1/dev/pty/m0		c	2	0
mknod $1/dev/pty/m1		c	2	1
mknod $1/dev/pty/m2		c	2	2
mknod $1/dev/pty/m3		c	2	3
mknod $1/dev/pty/m4		c	2	4
mknod $1/dev/pty/m5		c	2	5
mknod $1/dev/pty/m6		c	2	6
mknod $1/dev/pty/m7		c	2	7
mknod $1/dev/pty/m8		c	2	8
mknod $1/dev/pty/m9		c	2	9
mknod $1/dev/pty/m10	c	2	10
mknod $1/dev/pty/m11	c	2	11
mknod $1/dev/pty/m12	c	2	12
mknod $1/dev/pty/m13	c	2	13
mknod $1/dev/pty/m14	c	2	14
mknod $1/dev/pty/m15	c	2	15
[ -d $1/dev/tts ] || mkdir $1/dev/tts
mknod $1/dev/tts/0		c	4	64
mknod $1/dev/tts/1		c	4	65
mknod $1/dev/tty		c	5	0
mknod $1/dev/console	c	5	1
mknod $1/dev/ptmx		c	5	2
[ -d $1/dev/cua ] || mkdir $1/dev/cua
mknod $1/dev/cua/0		c	5	64
[ -d $1/dev/misc ] || mkdir $1/dev/misc
mknod $1/dev/misc/rtc	c	10	135
[ -d $1/dev/mtdblock ] || mkdir $1/dev/mtdblock
mknod $1/dev/mtdblock/0	b	31	0
mknod $1/dev/mtdblock/1	b	31	1
mknod $1/dev/mtdblock/2	b	31	2
mknod $1/dev/mtdblock/3	b	31	3
mknod $1/dev/mtdblock/4	b	31	4
mknod $1/dev/mtdblock/5	b	31	5
mknod $1/dev/mtdblock/6	b	31	6
mknod $1/dev/mtdblock/7	b	31	7
[ -d $1/dev/mtd ] || mkdir $1/dev/mtd
mknod $1/dev/mtd/0		c	90	0
mknod $1/dev/mtd/0ro	c	90	1
mknod $1/dev/mtd/1		c	90	2
mknod $1/dev/mtd/1ro	c	90	3
mknod $1/dev/mtd/2		c	90	4
mknod $1/dev/mtd/2ro	c	90	5
mknod $1/dev/mtd/3		c	90	6
mknod $1/dev/mtd/3ro	c	90	7
mknod $1/dev/mtd/4		c	90	8
mknod $1/dev/mtd/4ro	c	90	9
mknod $1/dev/mtd/5		c	90	10
mknod $1/dev/mtd/5ro	c	90	11
mknod $1/dev/mtd/6		c	90	12
mknod $1/dev/mtd/6ro	c	90	13
mknod $1/dev/mtd/7		c	90	14
mknod $1/dev/mtd/7ro	c	90	15
mknod $1/dev/ppp		c	108	0
[ -d $1/dev/pts ] || mkdir $1/dev/pts
mknod $1/dev/pts/0		c	136	0
mknod $1/dev/pts/1		c	136	1
mknod $1/dev/pts/2		c	136	2
mknod $1/dev/pts/3		c	136	3
mknod $1/dev/pts/4		c	136	4
mknod $1/dev/pts/5		c	136	5
mknod $1/dev/pts/6		c	136	6
mknod $1/dev/pts/7		c	136	7
[ -d $1/dev/net ] || mkdir $1/dev/net
mknod -m 0666 $1/dev/net/tun	c	10	200
