#!/bin/sh

# This program is called by the make files.  It creates the merge.h
# file which is included by netpbm.c.

echo "/* File generated by make_merge.sh */"
echo "/* in directory" `pwd` "*/"
echo

for MERGE_BINARY in $*; do
    echo "TRY(\"${MERGE_BINARY}\", main_${MERGE_BINARY});"
    done
